apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.fullname" . | quote }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
type: Opaque
stringData:
  NEXTCLOUD_ADMIN_USER: {{ .Values.appConfig.nextcloud.adminUser | quote }}
  NEXTCLOUD_ADMIN_PASSWORD: {{ .Values.appConfig.nextcloud.adminPass | quote }}
  POSTGRES_USER: {{ .Values.appConfig.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.appConfig.postgres.password | quote }}
