services:
  redis:
    image: redislabs/redismod
    container_name: db
    ports:
      - '6379:6379'
  web:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - .:/src
    depends_on:
      - redis