# syntax=docker/dockerfile:1.4
FROM python:3.8-slim-buster

RUN python3 -m pip install --user --upgrade pip
ENV PIP_ROOT_USER_ACTION=ignore
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install --assume-yes git

WORKDIR /src

COPY requirements.txt /src
RUN python3 -m pip install --no-cache-dir --user -r requirements.txt

COPY . /src

ENTRYPOINT ["python3"]
CMD ["app.py"]